name: Regenerate Files
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          set -euo pipefail
          git config --global user.email "theypsilon@gmail.com"
          git config --global user.name "The CI/CD Bot"
          ./.github/regenerate_files.sh
